function tsp_panel_label(ax, index)
text(ax, 0.02, 0.97, sprintf('(%c)', char(96+index)), ...
    'Units', 'normalized', 'VerticalAlignment', 'top', ...
    'FontWeight', 'bold', 'FontSize', 8.2);
end
