function tsp_figure_setup()
%TSP_FIGURE_SETUP IEEE-oriented, color-vision-friendly defaults.
set(groot, 'defaultAxesFontName', 'Helvetica', ...
    'defaultTextFontName', 'Helvetica', 'defaultAxesFontSize', 8, ...
    'defaultTextFontSize', 8, 'defaultAxesLineWidth', 0.75, ...
    'defaultLineLineWidth', 1.15, 'defaultAxesTickDir', 'out', ...
    'defaultAxesBox', 'off', 'defaultLegendBox', 'off');
end
